import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import api from '../api';
import { RadarChart, PolarGrid, PolarAngleAxis, Radar, ResponsiveContainer, Tooltip } from 'recharts';
import Logo from '../components/Logo';
import { normalizeUrl } from '../utils/url';

export default function PublicReport() {
  const { shareToken } = useParams();
  const [report, setReport] = useState(null);
  const [error, setError] = useState(null); // null | 'expired' | 'invalid'

  useEffect(() => {
    api.get(`/api/reports/share/${shareToken}`)
      .then(r => setReport(r.data))
      .catch(err => setError(err.response?.status === 410 ? 'expired' : 'invalid'));
  }, [shareToken]);

  if (error) return (
    <div className="min-h-screen flex items-center justify-center text-center">
      <div>
        <div className="text-5xl mb-4">{error === 'expired' ? '⏳' : '🔒'}</div>
        <p className="text-gray-600">
          {error === 'expired'
            ? 'This report link has expired. Ask the candidate to share an updated link.'
            : 'This report link is invalid.'}
        </p>
      </div>
    </div>
  );
  if (!report) return <div className="min-h-screen flex items-center justify-center text-gray-400">Loading...</div>;

  const data = report.llm_output_json;
  const radarData = [
    { subject: 'Performance', score: data.scores.overallPerformance },
    { subject: 'Teamwork', score: data.scores.teamwork },
    { subject: 'Communication', score: data.scores.communication },
    { subject: 'Problem Solving', score: data.scores.problemSolving },
    { subject: 'Leadership', score: data.scores.leadership },
  ];

  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-8">
          <div className="flex justify-center mb-2"><Logo height={36} /></div>
          <p className="text-gray-500 text-sm">Verified Reference Report</p>
        </div>

        <div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6">
          <div className="flex justify-between items-start">
            <h1 className="text-2xl font-bold">Reference Report</h1>
            <div className="text-center bg-teal-50 rounded-xl px-5 py-3">
              <div className="text-3xl font-bold text-teal-700">{data.confidenceScore}%</div>
              <div className="text-xs text-gray-500">Confidence</div>
            </div>
          </div>
          <div className="mt-5 bg-teal-50 rounded-xl p-5">
            <p className="text-gray-700 leading-relaxed">{data.executiveSummary}</p>
          </div>

          {report.resume_url && (
            <a href={normalizeUrl(report.resume_url)} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-sm text-teal-600 hover:underline mt-4">
              📄 View Resume →
            </a>
          )}
        </div>

        <div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6">
          <h2 className="font-semibold text-gray-800 mb-5">Competency Scores</h2>
          <ResponsiveContainer width="100%" height={280}>
            <RadarChart data={radarData}>
              <PolarGrid />
              <PolarAngleAxis dataKey="subject" />
              <Radar dataKey="score" stroke="#4f46e5" fill="#4f46e5" fillOpacity={0.25} />
              <Tooltip formatter={v => [`${v}/5`]} />
            </RadarChart>
          </ResponsiveContainer>
        </div>

        <div className="grid md:grid-cols-2 gap-5 mb-5">
          <div className="bg-white rounded-2xl border border-gray-200 p-6">
            <h2 className="font-semibold mb-3">💪 Key Strengths</h2>
            <ul className="space-y-2 text-sm text-gray-700">
              {data.keyStrengths.map((s, i) => <li key={i}><span className="text-green-500">✓ </span>{s}</li>)}
            </ul>
          </div>
          <div className="bg-white rounded-2xl border border-gray-200 p-6">
            <h2 className="font-semibold mb-3">🔄 Rehire Signal</h2>
            <div className="flex gap-6 mb-2">
              <div className="text-center"><div className="text-2xl font-bold text-green-600">{data.rehireSignal.yes}</div><div className="text-xs text-gray-500">Yes</div></div>
              <div className="text-center"><div className="text-2xl font-bold text-red-500">{data.rehireSignal.no}</div><div className="text-xs text-gray-500">No</div></div>
            </div>
            <p className="text-sm text-gray-600">{data.rehireSignal.context}</p>
          </div>
        </div>

        {report.linkedin_analysis_json && <ProfileSection p={report.linkedin_analysis_json} url={report.candidate_linkedin_url} />}

        <div className="text-center text-xs text-gray-400 mt-8">
          Generated by VouchMetrics · {new Date(report.created_at).toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}

function ProfileSection({ p, url }) {
  const strengthColor = { Beginner: 'text-gray-500', Intermediate: 'text-blue-600', Advanced: 'text-teal-600', Expert: 'text-indigo-600' };
  const scoreColor = p.profileScore >= 80 ? 'text-teal-700' : p.profileScore >= 60 ? 'text-blue-700' : 'text-yellow-700';
  const scoreBg = p.profileScore >= 80 ? 'bg-teal-50' : p.profileScore >= 60 ? 'bg-blue-50' : 'bg-yellow-50';

  return (
    <div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6">
      <div className="flex justify-between items-start mb-6">
        <div>
          <h2 className="font-semibold text-gray-800 text-lg">Professional Profile</h2>
          {url && (
            <a href={normalizeUrl(url)} target="_blank" rel="noopener noreferrer"
              className="text-xs text-teal-600 hover:underline mt-0.5 block">View LinkedIn →</a>
          )}
        </div>
        <div className={`text-center ${scoreBg} rounded-xl px-5 py-3`}>
          <div className={`text-3xl font-bold ${scoreColor}`}>{p.profileScore}</div>
          <div className="text-xs text-gray-500 mt-1">Profile Score</div>
        </div>
      </div>

      <p className="text-gray-700 text-sm leading-relaxed mb-6">{p.summary}</p>

      <div className="grid md:grid-cols-2 gap-6">
        <div className="space-y-3">
          {(p.currentTitle || p.currentCompany) && (
            <div>
              <div className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">Current Role</div>
              <div className="text-sm text-gray-800 font-medium">{p.currentTitle}</div>
              {p.currentCompany && <div className="text-sm text-gray-600">{p.currentCompany}</div>}
            </div>
          )}
          {p.experienceYears != null && (
            <div>
              <div className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">Experience</div>
              <div className="text-sm text-gray-800">{p.experienceYears} year{p.experienceYears !== 1 ? 's' : ''}</div>
            </div>
          )}
          {p.profileStrength && (
            <div>
              <div className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">Profile Strength</div>
              <div className={`text-sm font-semibold ${strengthColor[p.profileStrength] || 'text-gray-700'}`}>{p.profileStrength}</div>
            </div>
          )}
        </div>

        <div className="space-y-3">
          {p.topSkills?.length > 0 && (
            <div>
              <div className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">Top Skills</div>
              <div className="flex flex-wrap gap-1.5">
                {p.topSkills.map((s, i) => (
                  <span key={i} className="text-xs bg-gray-100 text-gray-700 px-2.5 py-1 rounded-full">{s}</span>
                ))}
              </div>
            </div>
          )}
          {p.educationHighlights?.length > 0 && (
            <div>
              <div className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">Education</div>
              <ul className="space-y-0.5">
                {p.educationHighlights.map((e, i) => (
                  <li key={i} className="text-sm text-gray-700">{e}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>

      {p.careerTrajectory && (
        <div className="mt-5 pt-5 border-t border-gray-100">
          <div className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">Career Trajectory</div>
          <p className="text-sm text-gray-700">{p.careerTrajectory}</p>
        </div>
      )}

      <p className="text-xs text-gray-400 mt-5 pt-4 border-t border-gray-100">
        Based on information the candidate shared directly — not independently verified.
      </p>
    </div>
  );
}
