import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import { RadarChart, PolarGrid, PolarAngleAxis, Radar, ResponsiveContainer, Tooltip } from 'recharts';

export default function PublicReport() {
  const { shareToken } = useParams();
  const [report, setReport] = useState(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    axios.get(`/api/reports/share/${shareToken}`)
      .then(r => setReport(r.data))
      .catch(() => setError(true));
  }, [shareToken]);

  if (error) return (
    <div className="min-h-screen flex items-center justify-center text-center">
      <div><div className="text-5xl mb-4">🔒</div><p className="text-gray-600">This report link is invalid or has expired.</p></div>
    </div>
  );
  if (!report) return <div className="min-h-screen flex items-center justify-center text-gray-400">Loading...</div>;

  const data = report.llm_output_json;
  const radarData = [
    { subject: 'Performance', score: data.scores.overallPerformance },
    { subject: 'Teamwork', score: data.scores.teamwork },
    { subject: 'Communication', score: data.scores.communication },
    { subject: 'Problem Solving', score: data.scores.problemSolving },
    { subject: 'Leadership', score: data.scores.leadership },
  ];

  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-8">
          <div className="text-2xl font-bold text-indigo-700 mb-1">eRefs<span className="text-gray-400">.ai</span></div>
          <p className="text-gray-500 text-sm">Verified Reference Report</p>
        </div>

        <div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6">
          <div className="flex justify-between items-start">
            <h1 className="text-2xl font-bold">Reference Report</h1>
            <div className="text-center bg-indigo-50 rounded-xl px-5 py-3">
              <div className="text-3xl font-bold text-indigo-700">{data.confidenceScore}%</div>
              <div className="text-xs text-gray-500">Confidence</div>
            </div>
          </div>
          <div className="mt-5 bg-indigo-50 rounded-xl p-5">
            <p className="text-gray-700 leading-relaxed">{data.executiveSummary}</p>
          </div>
        </div>

        <div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6">
          <h2 className="font-semibold text-gray-800 mb-5">Competency Scores</h2>
          <ResponsiveContainer width="100%" height={280}>
            <RadarChart data={radarData}>
              <PolarGrid />
              <PolarAngleAxis dataKey="subject" />
              <Radar dataKey="score" stroke="#4f46e5" fill="#4f46e5" fillOpacity={0.25} />
              <Tooltip formatter={v => [`${v}/5`]} />
            </RadarChart>
          </ResponsiveContainer>
        </div>

        <div className="grid md:grid-cols-2 gap-5 mb-5">
          <div className="bg-white rounded-2xl border border-gray-200 p-6">
            <h2 className="font-semibold mb-3">💪 Key Strengths</h2>
            <ul className="space-y-2 text-sm text-gray-700">
              {data.keyStrengths.map((s, i) => <li key={i}><span className="text-green-500">✓ </span>{s}</li>)}
            </ul>
          </div>
          <div className="bg-white rounded-2xl border border-gray-200 p-6">
            <h2 className="font-semibold mb-3">🔄 Rehire Signal</h2>
            <div className="flex gap-6 mb-2">
              <div className="text-center"><div className="text-2xl font-bold text-green-600">{data.rehireSignal.yes}</div><div className="text-xs text-gray-500">Yes</div></div>
              <div className="text-center"><div className="text-2xl font-bold text-red-500">{data.rehireSignal.no}</div><div className="text-xs text-gray-500">No</div></div>
            </div>
            <p className="text-sm text-gray-600">{data.rehireSignal.context}</p>
          </div>
        </div>

        <div className="text-center text-xs text-gray-400 mt-8">
          Generated by eRefs.ai · {new Date(report.created_at).toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}
