import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white border-b border-gray-200 px-8 py-4 flex justify-between items-center">
        <Link to="/" className="text-xl font-bold text-indigo-700">eRefs<span className="text-gray-400">.ai</span></Link>
      </nav>

      <main className="max-w-3xl mx-auto px-8 py-12">
        <h1 className="text-3xl font-bold mb-2">Terms & Conditions</h1>
        <p className="text-gray-400 text-sm mb-10">Last updated: June 2026</p>

        <div className="space-y-8 text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">1. Acceptance of Terms</h2>
            <p>By creating an account on eRefs.ai, you agree to these Terms & Conditions in full. If you do not agree, you must not use this platform. These terms apply to all users including job seekers, employers, and referrers.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">2. eRefs Responsibilities — Data Protection</h2>
            <p>eRefs.ai is committed to protecting the personal and professional data of all users. Specifically:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1 text-sm">
              <li>All data is encrypted in transit and at rest.</li>
              <li>Reference responses and AI-generated reports are accessible only to the requester and authorised parties.</li>
              <li>eRefs.ai will never sell, share, or disclose user data to third parties without explicit consent, except where required by law.</li>
              <li>Users may request deletion of their data at any time by contacting support.</li>
              <li>eRefs.ai uses industry-standard security practices to protect against unauthorised access, data breaches, and misuse.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">3. Employer Responsibilities — Account Security</h2>
            <p>As an employer using eRefs.ai, you are responsible for the security of your account. Specifically:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1 text-sm">
              <li>You must not share your username, password, or account access with any other person or organisation.</li>
              <li>You are solely responsible for all activity that occurs under your account.</li>
              <li>If you suspect unauthorised access to your account, you must notify eRefs.ai immediately and change your password.</li>
              <li>eRefs.ai is not liable for any loss or damage resulting from your failure to maintain account security.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Appropriate Use</h2>
            <p>You agree to use eRefs.ai only for legitimate professional reference checking purposes. You must not:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1 text-sm">
              <li>Use the platform to collect references without the candidate's knowledge or consent.</li>
              <li>Submit false, misleading, or defamatory reference responses.</li>
              <li>Attempt to reverse-engineer, scrape, or exploit the platform in any way.</li>
              <li>Use the platform for any unlawful purpose.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">5. AI-Generated Reports</h2>
            <p>Reports generated by eRefs.ai are produced using artificial intelligence and are intended as a decision-support tool only. eRefs.ai makes no guarantees about the accuracy or completeness of AI-generated reports. Hiring decisions must not be made solely on the basis of an eRefs report. You are responsible for exercising independent judgement.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">6. Beta Period</h2>
            <p>eRefs.ai is currently in beta. The platform is provided "as is" during this period. Features may change, and service interruptions may occur. We are not liable for any loss arising from service unavailability during the beta phase.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Changes to Terms</h2>
            <p>eRefs.ai reserves the right to update these Terms & Conditions at any time. Users will be notified of material changes by email. Continued use of the platform after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Contact</h2>
            <p>For any questions about these terms, please contact us at <a href="mailto:support@erefs.ai" className="text-indigo-600 hover:underline">support@erefs.ai</a>.</p>
          </section>

        </div>
      </main>

      <footer className="border-t border-gray-100 py-6 px-8 mt-10">
        <div className="max-w-3xl mx-auto text-sm text-gray-400">
          © {new Date().getFullYear()} eRefs.ai — All rights reserved
        </div>
      </footer>
    </div>
  );
}
